jobs:
  darkube_build_attackehw2_kianghassemi04_hamravesh-c13:
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root
    env:
      IMAGE_NAME: attacker
    runs-on: ubuntu-latest
    steps:
    - name: checkout commit
      uses: actions/checkout@v4
    - name: darkube-cli build & push
      run: |
        echo '${{secrets.DOCKER_AUTH_CONFIG}}' > /tmp/docker-auth.json
        darkube build --push -t $IMAGE_NAME:${GITHUB_SHA:0:7} -t $IMAGE_NAME:${GITHUB_REF_NAME} \
          --docker-auth-config /tmp/docker-auth.json --workdir . --file ./Dockerfile \
          --build-context .
  darkube_deploy_attackehw2_kianghassemi04_hamravesh-c13:
    container: hamravesh/darkube-cli:v1.1
    needs: darkube_build_attackehw2_kianghassemi04_hamravesh-c13
    runs-on: ubuntu-latest
    steps:
    - name: darkube-cli deploy
      run: darkube deploy --token ${{secrets.DEPLOY_TOKEN_ATTACKEHW2_KIANGHASSEMI04_HAMRAVESH_C13}}
        --app-id ${{secrets.APP_ID_ATTACKEHW2_KIANGHASSEMI04_HAMRAVESH_C13}} --image-tag
        ${GITHUB_SHA:0:7} --job-id ${GITHUB_RUN_ID}
'on':
  push:
    branches:
    - main
